import React from "react";

const FirstFloor = () => {
  return (
    <svg width="100%" viewBox="0 0 800 200" xmlns="http://www.w3.org/2000/svg">
      <title>Rooms</title>

      <g>
        <title>Premier étage</title>
        <rect
          strokeWidth="3"
          id="background"
          height="200"
          width="800"
          y="0"
          x="0"
          stroke="#000"
          fill="gray"
          className="background"
        />
        <rect
          stroke="#000"
          id="1"
          height="88"
          width="106.00001"
          y="2.5"
          x="2.5"
          strokeWidth="2"
          fill="gray"
          className="room"
        />
        <rect
          id="right_wall"
          height="28"
          width="377"
          y="170.5"
          x="421.5"
          strokeWidth="2"
          stroke="#000"
          fill="gray"
          className="wall"
        />
        <rect
          id="left_wall"
          height="29"
          width="377"
          y="169.5"
          x="1.5"
          strokeWidth="2"
          stroke="#000"
          fill="gray"
          className="wall"
        />
        <line
          id="svg_7"
          y2="175.5"
          x2="379.5"
          y1="175.5"
          x1="420.5"
          strokeWidth="2"
          stroke="#000"
          fill="none"
        />
        <line
          id="svg_8"
          y2="188.5"
          x2="379.5"
          y1="188.5"
          x1="422.5"
          strokeWidth="2"
          stroke="#000"
          fill="none"
        />
        <rect
          stroke="#000"
          id="2"
          height="88"
          width="106.00001"
          y="2.5"
          x="110.5"
          strokeWidth="2"
          fill="gray"
          className="room"
        />
        <rect
          stroke="#000"
          id="3"
          height="88"
          width="106.00001"
          y="2.5"
          x="217.5"
          strokeWidth="2"
          fill="gray"
          className="room"
        />
        <rect
          stroke="#000"
          id="4"
          height="88"
          width="106.00001"
          y="2.5"
          x="324.5"
          strokeWidth="2"
          fill="gray"
          className="room"
        />
        <rect
          stroke="#000"
          id="5"
          height="88"
          width="106.00001"
          y="2.5"
          x="432.5"
          strokeWidth="2"
          fill="gray"
          className="room"
        />
        <rect
          stroke="#000"
          id="6"
          height="88"
          width="106.00001"
          y="2.5"
          x="540.5"
          strokeWidth="2"
          fill="gray"
          className="room"
        />
        <rect
          stroke="#000"
          id="7"
          height="88"
          width="106.00001"
          y="2.5"
          x="648.5"
          strokeWidth="2"
          fill="gray"
          className="room"
        />
        <text
          textAnchor="start"
          fontFamily="Noto Sans JP"
          fontSize="24"
          id="svg_21"
          y="54.5"
          x="40.5"
          strokeWidth="0"
          stroke="#000"
          fill="black"
        >
          01
        </text>
        <text
          textAnchor="start"
          fontFamily="Noto Sans JP"
          fontSize="24"
          id="svg_24"
          y="55.5"
          x="147.5"
          strokeWidth="0"
          stroke="#000"
          fill="black"
        >
          02
        </text>
        <text
          textAnchor="start"
          fontFamily="Noto Sans JP"
          fontSize="24"
          id="svg_25"
          y="54.5"
          x="255.5"
          strokeWidth="0"
          stroke="#000"
          fill="black"
        >
          03
        </text>
        <text
          textAnchor="start"
          fontFamily="Noto Sans JP"
          fontSize="24"
          id="svg_26"
          y="57.5"
          x="360.5"
          strokeWidth="0"
          stroke="#000"
          fill="black"
        >
          04
        </text>
        <text
          textAnchor="start"
          fontFamily="Noto Sans JP"
          fontSize="24"
          id="svg_27"
          y="55.5"
          x="470.5"
          strokeWidth="0"
          stroke="#000"
          fill="black"
        >
          05
        </text>
        <text
          textAnchor="start"
          fontFamily="Noto Sans JP"
          fontSize="24"
          id="svg_28"
          y="52.5"
          x="572.5"
          strokeWidth="0"
          stroke="#000"
          fill="black"
        >
          06
        </text>
        <text
          textAnchor="start"
          fontFamily="Noto Sans JP"
          fontSize="24"
          id="svg_29"
          y="52.5"
          x="682.5"
          strokeWidth="0"
          stroke="#000"
          fill="black"
        >
          07
        </text>
      </g>
    </svg>
  );
};

export default FirstFloor;
